// Generates src/site/ph.jsx: just the Phosphor icons (and styles) the website
// uses, instead of the whole icon library. Run `node scripts/build-icons.mjs`
// after adding an icon to the list below.
import { readFileSync, writeFileSync } from 'node:fs'

const ICONS = {
  duotone: [
    'AirplaneTilt', 'Boat', 'Buildings', 'CalendarBlank', 'Certificate', 'ChartBar', 'CheckCircle', 'Clock', 'EnvelopeSimple',
    'Globe', 'GlobeHemisphereEast', 'Handshake', 'Info', 'Leaf', 'MapPin', 'Medal', 'Package', 'Phone', 'Plant', 'Quotes',
    'Scales', 'SealCheck', 'ShieldCheck', 'Star', 'Train', 'TrendUp', 'Truck', 'UsersThree', 'Warehouse', 'WhatsappLogo',
  ],
  bold: ['ArrowDownLeft', 'ArrowRight', 'ArrowUpRight', 'CheckCircle', 'List', 'PaperPlaneTilt', 'Plus', 'TrendUp', 'X'],
  fill: ['WhatsappLogo'],
  regular: ['Copy'],
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
const svgs = {}
const defaults = {}
for (const [weight, names] of Object.entries(ICONS)) {
  for (const name of names) {
    const file = `node_modules/@phosphor-icons/core/assets/${weight}/${kebab(name)}${weight === 'regular' ? '' : `-${weight}`}.svg`
    const inner = readFileSync(file, 'utf8').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()
    svgs[`${name}:${weight}`] = inner
    defaults[name] ??= weight
  }
}

const names = Object.keys(defaults).sort()
const out = `// Generated by scripts/build-icons.mjs from Phosphor Icons (MIT licence,
// @phosphor-icons/core). Only the icons and styles the website uses.
const P = ${JSON.stringify(svgs, null, 0).replace(/","/g, '",\n  "').replace(/^\{/, '{\n  ').replace(/\}$/, ',\n}')}

function icon(name, fallback) {
  const Icon = ({ size = 24, weight = fallback, ...rest }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" width={size} height={size} fill="currentColor" aria-hidden="true"
      dangerouslySetInnerHTML={{ __html: P[\`\${name}:\${weight}\`] ?? P[\`\${name}:\${fallback}\`] }} {...rest} />
  )
  return Icon
}

${names.map((n) => `export const ${n} = icon('${n}', '${defaults[n]}')`).join('\n')}
`
writeFileSync('src/site/ph.jsx', out)
console.log(`${Object.keys(svgs).length} icon styles, ${Math.round(out.length / 1024)} KB`)
